### ISSUE TITLE
remove unused attributes from html element

### ISSUE THREAD

**Issue by 0prodigy** [Mikearaya/youtube_clone#6]
- Make sure you give correct path for link style sheet
- You can remove unused attributes from html
- Go for some other fonts so you can have the similar look as required. 

**You did great job and your code is looking pretty.**

**Comment by Mikearaya** [comment]
- fixed correct stylesheet path 
- aria-hidden=true is used for screen reader so it's useful
- we will try to find similar font

**Comment by Mikearaya** [comment]
used the font used by youtube youtube roboto
